# Generated by Django 2.0.7 on 2019-02-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=380, null=True)),
                ('section_number', models.IntegerField(blank=True, null=True)),
                ('sub_section_number', models.IntegerField(blank=True, null=True)),
                ('question_number', models.IntegerField(blank=True, null=True)),
                ('answer_number', models.IntegerField(blank=True, null=True)),
                ('interview_id', models.CharField(blank=True, max_length=10, null=True)),
                ('field_time', models.CharField(blank=True, db_column='_time', max_length=8, null=True)),
            ],
            options={
                'db_table': 'answers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=40)),
                ('interview_id', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('household_id', models.CharField(blank=True, max_length=9, null=True, unique=True)),
                ('first_interview', models.CharField(blank=True, max_length=20, null=True)),
                ('coop_union', models.CharField(blank=True, max_length=45, null=True)),
                ('prime_coop', models.CharField(blank=True, max_length=45, null=True)),
                ('latitude', models.CharField(blank=True, max_length=16, null=True)),
                ('longitude', models.CharField(blank=True, max_length=16, null=True)),
                ('current_section', models.CharField(blank=True, max_length=8, null=True)),
                ('field_time', models.CharField(blank=True, db_column='_time', max_length=8, null=True)),
                ('field_date', models.CharField(blank=True, db_column='_date', max_length=35, null=True)),
                ('year', models.CharField(blank=True, db_column='year', max_length=35, null=True)),
            ],
            options={
                'db_table': 'meta_data',
                'managed': True,
            },
        ),
    ]
